<?xml version="1.0" encoding="UTF-8"?><testsuite errors="0" failures="1" name="starter.runner.Test_Login" skipped="0" tests="2" time="18.3" timestamp="2020-03-05 04:35:01"><testcase classname="starter.runner.Test_Login" name="Prueba de loguearse."/><testcase classname="starter.runner.Test_Login" name="Prueba de loguearse. Otras credenciales"><failure type="junit.framework.AssertionFailedError"/><system-err>null&#13;
junit.framework.Assert.fail(Assert.java:55)&#13;
junit.framework.Assert.assertTrue(Assert.java:22)&#13;
junit.framework.Assert.assertTrue(Assert.java:31)&#13;
starter.runner.Test_Login.Test_Loguearse_otras_Credenciales(Test_Login.java:78)&#13;
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)&#13;
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
</system-err></testcase></testsuite>